/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 bookshelf.gltf 
Author: Brandon Westlake (https://sketchfab.com/dr.badass2142)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/dusty-old-bookshelf-free-6c5ac2547db34c3c81b2e4808b000386
Title: Dusty Old Bookshelf (FREE)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/bookshelf.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.Old_Dusty_Bookshelf_Spiderwebs_Mat} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.Old_Dusty_Bookshelf_Mat} />
    </group>
  )
}

useGLTF.preload('/bookshelf.gltf')
